#!/bin/bash

version=$1

if [ "x$version" == "x" ]; then
  echo "Usage: $0 <version>"
  exit 1
fi

. /usr/local/src/update/lib/functions

cd /usr/local/src/
clean_oldsrc openssl-$version

download_src "http://www.openssl.org/source/openssl-$version.tar.gz" openssl-$version.tar.gz
tar -xvzf openssl-$version.tar.gz
cd openssl-$version
if [ -f /usr/local/src/openssl-pod.patch ]; then
   patch -p1 < ../openssl-pod.patch
fi
./config shared no-ssl2 --prefix=/usr/local/openssl/$version -fPIC
if [ $? -eq 1 ]; then
  echo "ERROR config failed..."
	exit 1
fi
make
if [ $? -eq 1 ]; then
  echo "ERROR make failed..."
	exit 1
fi
make install
if [ $? -eq 1 ]; then
  echo "ERROR make install failed..."
	exit 1
fi

cd /usr/local/openssl
rm -f current
ln -s $version current

