#!/bin/bash

uversion=$1

if [ "x$uversion" == "x" ]; then
	echo "Usage: $0 <version>"
	exit 1
fi

. $(dirname $0)/config.sh
. $(dirname $0)/lib/functions

init $uversion

cd $spath

clean_oldsrc unbound-$uversion
download_src "http://unbound.net/downloads/unbound-$uversion.tar.gz" unbound-$uversion.tar.gz
extract_and_compile unbound $uversion "--prefix=$ipath/unbound/$uversion --with-ssl=$ipath/openssl/current --with-chroot-dir=/var/lib/unbound --disable-gost"

cd $ipath/unbound/$uversion/etc
ln -s /etc/unbound/unbound.conf .

cd $ipath/unbound
/etc/init.d/unbound stop
rm -f current
ln -s $uversion current
/etc/init.d/unbound start
