#!/bin/bash

mariadb_version=$1

if [ "x$mariadb_version" == "x" ]; then
	echo "Usage: $0 <mariadb version>"
	exit 1
fi

. /usr/local/src/update/lib/functions

# make a backup of mysql databases
function make_backup () {
	echo -en "Will make a backup of you database...."
  /opt/scripts/backup/mysql_backup.sh
	if [ $? -eq 1 ]; then
		echo "ERROR mysql_backup failed..."
		exit 1
	fi
	echo "Your backup is at /var/backups/mysql"
}

mkdir -p /usr/local/src/mariadb/ && cd /usr/local/src/mariadb
clean_oldsrc mariadb-$mariadb_version
download_src "https://downloads.mariadb.org/f/mariadb-$mariadb_version/kvm-tarbake-jaunty-x86/mariadb-$mariadb_version.tar.gz/from/http:/mirror3.layerjet.com/mariadb" mariadb-$mariadb_version.tar.gz

# extract manually
tar -xzvf mariadb-$mariadb_version.tar.gz
cd mariadb-$mariadb_version/BUILD && ./autorun.sh
cd .. && ./configure --prefix=/usr/local/mariadb/$mariadb_version --with-mysqld-user=mysql --with-mysqlmanager --enable-profiling --with-plugins=myisam,archive,blackhole,csv,ibmdb2i,innodb_plugin,aria,myisammrg,xtradb,federated,partition,pbxt
if [ $? -ge 1 ]; then
   echo "configure failed."
   exit 1
fi
make
if [ $? -ge 1 ]; then
  echo "make failed."
  exit 1
fi

make install
if [ $? -ge 1 ]; then
  echo "make install failed."
  exit 1
fi

pgrep mysql > /dev/null 2>&1
if [ $? == 0 ]; then
	make_backup
fi

# relink
/etc/init.d/mysql stop
rm /usr/local/mariadb/current 
ln -s /usr/local/mariadb/$mariadb_version /usr/local/mariadb/current
/etc/init.d/mysql start


