#!/bin/bash

bg_version=$1

if [ "x$bg_version" == "x" ]; then
	echo "Usage: $0 <bogofilter version> "
	exit 1
fi

. $(dirname $0)/config.sh
. $(dirname $0)/lib/functions

init $bg_version

cd $spath
clean_oldsrc bogofilter-$bg_version
download_src "http://downloads.sourceforge.net/project/bogofilter/bogofilter-$bg_version/bogofilter-$bg_version.tar.bz2?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fbogofilter%2Ffiles%2Fbogofilter-1.2.4%2F&ts=1392990007&use_mirror=garr" bogofilter-$bg_version.tar.bz2

extract_and_compile bogofilter $bg_version "--prefix=$ipath/bogofilter/$bg_version"
# relink bogofilter
cd $ipath/bogofilter

rm -f current
ln -s $bg_version current

cd $ipath/bogofilter/current/etc/
ln -s /etc/bogofilter/bogofilter.cf .

# clean up
rm -rf $spath/bogofilter-$bg_version
