#!/bin/bash

uversion=$1
ldnsuversion=$2

if [ "x$uversion" == "x" -o "x$ldnsuversion" == "x" ]; then
	echo "Usage: $0 <version> <ldns uversion>"
	exit 1
fi

. /usr/local/src/update/lib/functions

mkdir -p /usr/local/src && cd /usr/local/src

clean_oldsrc ldns-$ldnsuversion
download_src "http://www.nlnetlabs.nl/downloads/ldns/ldns-$ldnsuversion.tar.gz" ldns-$ldnsuversion.tar.gz
extract_and_compile ldns $ldnsuversion "--prefix=/usr/local/ldns/$ldnsuversion --with-ssl=/usr/local/openssl/current"

clean_oldsrc unbound-$uversion
download_src "http://unbound.net/downloads/unbound-$uversion.tar.gz" unbound-$uversion.tar.gz
extract_and_compile unbound $uversion "--prefix=/usr/local/unbound/$uversion --with-ssl=/usr/local/openssl/current --with-chroot-dir=/var/lib/unbound --disable-gost --with-ldns=/usr/local/ldns/$ldnsuversion"

cd /usr/local/unbound/$uversion/etc
ln -s /etc/unbound/unbound.conf .

cd /usr/local/unbound
/etc/init.d/unbound stop
rm -f current
ln -s $uversion current
/etc/init.d/unbound start
