#!/bin/bash

dovecot_version=$1
pig_version=$2

if [ "x$dovecot_version" == "x" -o "x$pig_version" == "x" ]; then
	echo "Usage: $0 <dovecot version> <pigeonhole version>"
	exit 1
fi

. $(dirname $0)/config.sh
. $(dirname $0)/lib/functions

init $dovecot_version

mkdir -p $spath/dovecot && cd $spath/dovecot
clean_oldsrc dovecot-$dovecot_version

download_src "http://dovecot.org/releases/2.2/dovecot-$dovecot_version.tar.gz" dovecot-$dovecot_version.tar.gz

extract_and_compile dovecot $dovecot_version "--prefix=$ipath/dovecot/$dovecot_version --with-shadow --with-pam --with-ssl=openssl --with-mysql --sysconfdir=/etc"

# compile pigeon
# clean up the source directory
clean_oldsrc dovecot-2.2-pigeonhole-$pig_version

download_src "http://pigeonhole.dovecot.org/releases/2.2/dovecot-2.2-pigeonhole-$pig_version.tar.gz" dovecot-2.2-pigeonhole-$pig_version.tar.gz

extract_and_compile dovecot-2.2-pigeonhole $pig_version "--with-dovecot=$ipath/dovecot/$dovecot_version/lib/dovecot"

# relink dovecot
cd $ipath/dovecot/$dovecot_version
ln -s /etc/dovecot etc
./bin/doveconf -c $ipath/dovecot/$dovecot_version/etc/dovecot.conf
if [ $? -ne 0 ]; then
  echo "Configuration issues. Don't restart dovecot"
  exit 0
fi

cd $ipath/dovecot
if [ -f /etc/init.d/dovecot ]; then
  /etc/init.d/dovecot stop
  # dovecot doesn't stop savely
  pkill -9 -f dovecot
else
  systemctl=$(which systemctl)
  $systemctl stop dovecot
  pkill -9 -f dovecot
fi
rm -f current
ln -s $dovecot_version current
if [ -f /etc/init.d/dovecot ]; then
  /etc/init.d/dovecot start
else
  systemctl=$(which systemctl)
  $systemctl start dovecot
fi
