#!/bin/bash

version=$1
restart=$2

if [ "x$version" == "x" ]; then
  echo "Usage: $0 <version> [restart]"
  echo "Example: $0 7u11"
  exit 1
fi

. $(dirname $0)/config.sh
. $(dirname $0)/lib/functions


# split version
IFS="u"
set -- $version
majorv=$1
shift
minorv=$@

IFS=''

init jdk1.$majorv.0_$minorv

# stop all
if [ "x$restart" != "x" ]; then
  /etc/init.d/tomcat stop
  /etc/init.d/benno-smtp stop
  /etc/init.d/red5-server stop
fi

mkdir -p $ipath/java
cd $ipath/java
if [ ! -f "$spath/jdk-${majorv}u${minorv}-linux-x64.tar.gz" ]; then
  echo "You will need to upload jdk-${majorv}u${minorv}-linux-x64.tar.gz to $spath"
  exit 1
fi
tar -xzvf $spath/jdk-${majorv}u${minorv}-linux-x64.tar.gz
rm -f current
ln -s jdk1.$majorv.0_$minorv current
chown -R root: jdk1.$majorv.0_$minorv

export JAVA_HOME=$ipath/java/current
if [ "x$restart" != "x" ]; then
  sleep 4
  /etc/init.d/tomcat start
  /etc/init.d/benno-smtp start
  /etc/init.d/red5-server start
fi
