#!/bin/bash

version=$1
restart=$2

if [ "x$version" == "x" ]; then
  echo "Usage: $0 <version> [restart]"
  echo "Example: $0 7u11"
  exit 1
fi

# split version
IFS="u"
set -- $version
majorv=$1
shift
minorv=$@

# stop all
if [ "x$restart" != "x" ]; then
  /etc/init.d/tomcat stop
  /etc/init.d/benno-smtp stop
  /etc/init.d/red5-server stop
fi

mkdir /usr/local/java
cd /usr/local/java
tar -xzvf /usr/local/src/jdk-${majorv}u${minorv}-linux-x64.tar.gz
rm -f current
ln -s jdk1.$majorv.0_$minorv current
chown -R root: jdk1.$majorv.0_$minorv

export JAVA_HOME=/usr/local/java/current
if [ "x$restart" != "x" ]; then
  sleep 4
  /etc/init.d/tomcat start
  /etc/init.d/benno-smtp start
  /etc/init.d/red5-server start
fi
