#!/bin/bash

ms_version=$1
apache_version=$2

if [ "x$ms_version" == "x" -o "x$apache_version" == "x" ]; then
	echo "Usage: $0 <modsecurity version> <apache version>"
	exit 1
fi

# compile modsecurity
cd /usr/local/src/modsecurity-apache_$ms_version
./configure --with-apxs=/usr/local/apache2/$apache_version/bin/apxs
make
if [ $? -eq 1 ]; then
	echo "ERROR make failed..."
	exit 1
fi
make install
if [ $? -eq 1 ]; then
	echo "ERROR make install failed..."
	exit 1
fi
