#!/bin/bash


if [ -z "$1" -o -z "$2" ]; then
  echo "Usage: $0 <modx version> <path to site>"
  exit 1
fi

version=$1
site=$2

cd /usr/local/src
if [ ! -f modx-$version-pl.zip ]; then
  wget http://modx.com/download/direct/modx-$version-pl.zip
fi

if [ $? -ge 1 ]; then
  echo "Couldn't download file"
  exit 1
fi

unzip modx-$version-pl.zip


rsync -alvz modx-$version-pl/ $site
chown -R www-data: $site

rm -rf modx-$version-pl
