#!/bin/bash

bg_version=$1

if [ "x$bg_version" == "x" ]; then
	echo "Usage: $0 <bogofilter version> "
	exit 1
fi

cd /usr/local/src/
# compile dovecot
tar -xjvf bogofilter-$bg_version.tar.bz2
cd bogofilter-$bg_version
./configure --prefix=/usr/local/bogofilter/$bg_version
make
if [ $? -eq 1 ]; then
	echo "ERROR make bogofilter failed..."
	exit 1
fi
make install
if [ $? -eq 1 ]; then
	echo "ERROR make install bogofilter failed..."
	exit 1
fi

# relink bogofilter
cd /usr/local/bogofilter

rm -f current
ln -s $bg_version current

cd /usr/local/bogofilter/current/etc/
ln -s /etc/bogofilter/bogofilter.cf .

# clean up
rm -rf /usr/local/src/bogofilter-$bg_version
