#!/bin/bash
tomcat_version=$1

if [ "x$tomcat_version" == "x" ]; then
	echo "Usage: $0 <tomcat version> "
	exit 1
fi

cd /usr/local/src/
wget http://mirror.lwnetwork.org.uk/APACHE/tomcat/tomcat-7/v$tomcat_version/bin/apache-tomcat-$tomcat_version.tar.gz 
tar -xzvf apache-tomcat-$tomcat_version.tar.gz
mv apache-tomcat-$tomcat_version /usr/local/tomcat/$tomcat_version
cp /usr/local/src/bennosearch/bennosearch.war /usr/local/tomcat/$tomcat_version/webapps/

cd /usr/local/tomcat
chown -R tomcat:tomcat $tomcat_version
/etc/init.d/tomcat stop
/usr/bin/pkill -9 -f tomcat
rm current && ln -s $tomcat_version current
/etc/init.d/tomcat start
sleep 10
cp /usr/local/src/bennosearch/application*.xml /usr/local/tomcat/current/webapps/bennosearch/WEB-INF/
cp /usr/local/src/bennosearch/server.xml /usr/local/tomcat/current/conf/
/etc/init.d/tomcat stop
sleep 5
/etc/init.d/tomcat start
