#!/bin/bash

# default configure
# ./configure --prefix=/usr/local/zabbix/2.0.1 --enable-agent --enable-server --with-libcurl --with-net-snmp --with-ssh2 --with-mysql --enable-proxy --enable-java
version=$1


if [ "x$version" = "x" ]; then
	echo "Usage: $0 <version>"
	exit 1
fi

destdir=/usr/local/zabbix/$version
builddir=/usr/local/src/zabbix

wget http://downloads.sourceforge.net/project/zabbix/ZABBIX%20Latest%20Stable/$version/zabbix-$version.tar.gz -O /usr/local/src/zabbix/zabbix-$version.tar.gz
if [ ! -f $builddir/zabbix-$version.tar.gz ]; then
	echo "Source file zabbix-$version.tar.gz doesn't exist"
	exit 1
fi

cd $builddir
tar -xzvf zabbix-$version.tar.gz
cd zabbix-$version
export PATH=$PATH:/usr/local/java/current/bin/
./configure --prefix=$destdir --enable-agent --enable-server --with-libcurl --with-net-snmp --with-ssh2 --with-mysql --enable-proxy --enable-java
make
if [ $? -eq 1 ]; then
	echo "ERROR make failed..."
	exit 1
fi
make install
if [ $? -eq 1 ]; then
	echo "ERROR make install failed..."
	exit 1
fi

# copy frontend
cp -R frontends/php $destdir/frontends
rm -f $destdir/etc/zabbix_agentd.conf $destdir/etc/zabbix_server.conf
ln -s /etc/zabbix/zabbix_agentd.conf $destdir/etc/
ln -s /etc/zabbix/zabbix_server.conf $destdir/etc/

# restart zabbix
/etc/init.d/zabbix-server stop
/etc/init.d/zabbix-agent stop
sleep 3
rm -f /usr/local/zabbix/current && ln -s $destdir /usr/local/zabbix/current
/etc/init.d/zabbix-server start
sleep 3
/etc/init.d/zabbix-agent start

# change ownership of frontend
chown -R www-data: /usr/local/zabbix/current/frontends

# clean up
rm -rf /usr/local/src/zabbix/zabbix-$version
