#!/bin/bash
# test
dovecot_version=$1
pig_version=$2

if [ "x$dovecot_version" == "x" -o "x$pig_version" == "x" ]; then
	echo "Usage: $0 <dovecot version> <pigeonhole version>"
	exit 1
fi

cd /usr/local/src/dovecot
wget http://dovecot.org/releases/2.2/dovecot-$dovecot_version.tar.gz
# compile dovecot
tar -xzvf dovecot-$dovecot_version.tar.gz
cd dovecot-$dovecot_version
./configure --prefix=/usr/local/dovecot/$dovecot_version --with-shadow --with-pam --with-ssl=openssl --sysconfdir=/etc
make
if [ $? -eq 1 ]; then
	echo "ERROR make dovecot failed..."
	exit 1
fi
make install
if [ $? -eq 1 ]; then
	echo "ERROR make install dovecot failed..."
	exit 1
fi

# compile pigeon
cd /usr/local/src/dovecot
wget http://www.rename-it.nl/dovecot/2.2/dovecot-2.2-pigeonhole-$pig_version.tar.gz
tar -xzvf dovecot-2.2-pigeonhole-$pig_version.tar.gz
cd dovecot-2.2-pigeonhole-$pig_version
./configure --with-dovecot=/usr/local/dovecot/$dovecot_version/lib/dovecot
make
if [ $? -eq 1 ]; then
	echo "ERROR make pigeonhole failed..."
	exit 1
fi
make install
if [ $? -eq 1 ]; then
	echo "ERROR make install pigeonhole failed..."
	exit 1
fi

# relink dovecot
cd /usr/local/dovecot/$dovecot_version
ln -s /etc/dovecot etc
./bin/doveconf -c /usr/local/dovecot/$dovecot_version/etc/dovecot.conf
if [ $? -ne 0 ]; then
  echo "Configuration issues. Don't restart dovecot"
  exit 0
fi

cd /usr/local/dovecot
/etc/init.d/dovecot stop
rm -f current
ln -s $dovecot_version current
/etc/init.d/dovecot start
