#!/bin/bash

oc_version=$1

if [ "x$oc_version" == "x" ]; then
	echo "Usage: $0 <owncloud version>"
	exit 1
fi

cd /usr/local/src
wget http://download.owncloud.org/community/owncloud-$oc_version.tar.bz2
tar -xjvf owncloud-$oc_version.tar.bz2
mv owncloud /var/www/owncloud/$oc_version

# copy data
rsync -alvz /var/www/owncloud/current/data/ /var/www/owncloud/$oc_version

# copy config
cp /var/www/owncloud/current/config/config.php /var/www/owncloud/$oc_version/config/

chown -R www-data: /var/www/owncloud/$oc_version
# relink owncloud
#cd /var/www/owncloud
#rm -f current
#ln -s $oc_version current

echo "Done"

