#!/bin/bash
#
# logstats		Log File Monitor for RRI
#
# chkconfig: 2345 78 54
# description: Provides a log file monitor for RRI
#
### BEGIN INIT INFO
# Provides: logstats
# Required-Start: $local_fs $network $syslog
# Required-Stop: $local_fs $syslog
# Should-Start: $syslog
# Should-Stop: $network $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Log-File Monitor for RRI
# Description:       
#		     
### END INIT INFO

# source function library
. /etc/rc.d/init.d/functions

RETVAL=0
prog="logstats.pl"
lockfile=/var/lock/subsys/$prog

# Some functions to make the below more readable
LOGSTAT=/usr/sbin/logstats.pl
OPTIONS="-c /etc/logstats.cfg"
PID_FILE=/var/run/logstats.pl.pid

start()
{
	echo -n $"Starting $prog: "
	daemon $LOGSTAT $OPTIONS
	RETVAL=$?
	[ $RETVAL -eq 0 ] && touch $lockfile
	echo
	return $RETVAL
}

stop()
{
	echo -n $"Stopping $prog: "
	if [ -n "`pidfileofproc $LOGSTAT`" ] ; then
	    pkill -QUIT -f $LOGSTAT
	else
	    failure $"Stopping $prog"
	fi
	RETVAL=$?
	[ $RETVAL -eq 0 ] && rm -f $lockfile && rm -f $PID_FILE
	echo
}

restart() {
	stop
	start
}

reload () {
	pkill -HUP -f $LOGSTAT
}
	

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	reload)
		reload
		;;
	status)
		status $LOGSTAT
		;;
	*)
		echo $"Usage: $0 {start|stop|restart|reload|status}"
		RETVAL=2
esac
exit $RETVAL
