#!/usr/bin/expect

set user thorstek
set pass test
set host [lindex $argv 0]

spawn ssh -q ${user}@${host}
expect { 
  "*?assword"  {
    send "${pass}\r"
    expect "${user}@"
    send "ls -l \r"
    send "sudo su -\r"
    expect "*?assword"
    send "${pass}\r"
  } 
  "${user}@" {
    send "sudo su -\r"
    expect "*?assword"
    send "${pass}\r"
  }
}
  
interact
