#!/bin/bash

# default configure
# ./configure --prefix=/usr/local/zabbix/2.0.1 --enable-agent --enable-server --with-libcurl --with-net-snmp --with-ssh2 --with-mysql --enable-proxy --enable-java
version=$1


if [ "x$version" = "x" ]; then
	echo "Usage: $0 <verson>"
	exit 1
fi

destdir=/usr/local/zabbix/$version
builddir=/usr/local/src/zabbix

if [ ! -f $builddir/zabbix-$version.tar.gz ]; then
	echo "Source file zabbix-$version.tar.gz doesn't exist"
	exit 1
fi

cd $builddir
tar -xzvf zabbix-$version.tar.gz
cd zabbix-$version
export PATH=$PATH:/usr/local/java/jdk1.7.0_05/bin/
./configure --prefix=$destdir --enable-agent --enable-server --with-libcurl --with-net-snmp --with-ssh2 --with-mysql --enable-proxy --enable-java
make
make install

# copy frontend
cp -R frontends/php $destdir/frontends
rm -f $destdir/etc/zabbix_agentd.conf $destdir/etc/zabbix_server.conf
ln -s /etc/zabbix/zabbix_agentd.conf $destdir/etc/
ln -s /etc/zabbix/zabbix_server.conf $destdir/etc/

# restart zabbix
/etc/init.d/zabbix-server stop
/etc/init.d/zabbix-agent stop
sleep 3
rm -f /usr/local/zabbix/current && ln -s $destdir /usr/local/zabbix/current
/etc/init.d/zabbix-server start
sleep 3
/etc/init.d/zabbix-agent start

# change ownership of frontend
chown -R zabbix: /usr/local/zabbix/current/frontends

# clean up
rm -rf /usr/local/src/zabbix/zabbix-$version
