#!/bin/bash

ms_version=$1
apache_version=$2

if [ "x$ms_version" == "x" -o "x$apache_version" == "x" ]; then
	echo "Usage: $0 <modsecurity version> <apache version>"
	exit 1
fi

# compile modsecurity
cd /usr/local/src/modsecurity-apache_$ms_version
./configure --with-apxs=/usr/local/apache2/$apache_version/bin/apxs
make
#make install

# relink everything
#cd /usr/local/php5/$php_version/lib
#ln -s /etc/php5/apache2/php.ini ./
#cd /usr/local/php5
#rm -f current && ln -s ./$php_version ./current

#if [ ! -f /usr/local/php5/current/lib/php.ini ]; then
#	echo "NO php.ini linked to current"
#fi
#apachectl -t
